### ISSUE TITLE
Clean-up post extraction from Kleros v2

### ISSUE THREAD

**Issue by jaybuidl** [kleros/vea#36]
Relates to https://github.com/kleros/kleros-v2/issues/414

- [x] App-agnostic renames (Home -> Sender, Foreign -> Receiver)
- [ ] Mocks for the IReceiverGateway and ISenderGateway
- [ ] Deploy scripts for Arbitrum to Mainnet: removal of Kleros-related contracts, nounces fix
- [ ] Test scripts: removal of Kleros-related code 
- [x] Rinkeby network removal
