### ISSUE TITLE
New bridge from Arbitrum Goerli to Chiado: happy path

### ISSUE THREAD

**Issue by jaybuidl** [kleros/vea#57]
- [x] ArbiGoerli -> Chiado: creation of the contract pairs
- [x] ArbiGoerli -> Chiado: deployment scripts
- [x] ArbiGoerli -> Chiado: deployment
